name: CDC ICATT update nightly cronjob

on:
  push:
    branches:
      - main
  schedule:
    - cron: '55 22 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          sudo apt-get install -y curl

      - name: Running backup script
        run: |
          bash backup.sh ${GITHUB_WORKSPACE}

      - name: Commit ICATT Site changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: Github Action Bot
          author_email: noreply@github.com
          message: 'Nightly update of raw COVID Test Sites changes'
          add: 'data/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
